### ISSUE TITLE
Not released on packagist

### ISSUE THREAD

**Issue by Kocal** [symfony/psr7-pack#1]
Hi!

I'm trying to install the pack but it's not present on Packagist:
![image](https://user-images.githubusercontent.com/2103975/112102222-38e17b80-8ba8-11eb-86fe-7ddd73261270.png)

Resulting this error message:
![image](https://user-images.githubusercontent.com/2103975/112102258-472f9780-8ba8-11eb-89d3-6dd27e0153f5.png)

Friendly ping @nicolas-grekas, thanks!

**Comment by fabpot** [comment]
Registered now.

**Comment by Kocal** [comment]
Thanks!
